/*
 * This source file was generated by the Gradle 'init' task
 */
package estudiante;

import java.util.ArrayList;
import java.util.Scanner;

import estudiante.model.Estudiante;

public class App {

    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);

        System.out.println("Bienvenido al sistema de gestión de estudiantes");

        int numeroEstudiantes;

        do {
            System.out.print("Ingrese el número de estudiantes: ");
            numeroEstudiantes = sc.nextInt();
            if (numeroEstudiantes <= 0) {
                System.out.println("Por favor, ingrese un número válido de estudiantes.");
            }
        } while (numeroEstudiantes <= 0);

        ArrayList<Estudiante> listaEstudiantes = new ArrayList<>();


        for (int i = 0; i < numeroEstudiantes; i++) {
            sc.nextLine();
            System.out.println("Ingrese los datos del estudiante " + (i + 1) + ":");

            System.out.print("Nombre: ");
            String nombre = sc.nextLine();

            System.out.print("Edad: ");
            int edad = sc.nextInt();

            System.out.print("Nota Final: ");
            double notaFinal = sc.nextDouble();

            Estudiante estudiante = new Estudiante(nombre, edad, notaFinal);
            listaEstudiantes.add(estudiante);
        }


        while (true) {
            System.out.println("\nMenú:");
            System.out.println("1. Mostrar información de todos los estudiantes");
            System.out.println("2. Mostrar estudiantes aprobados");
            System.out.println("3. Salir");
            System.out.print("Seleccione una opción: ");
            int opcion = sc.nextInt();

            if (opcion == 1) {
                for (Estudiante estudiante : listaEstudiantes) {
                    estudiante.mostrarInformacion();
                    System.out.println("-----------------------");
                }
            } else if (opcion == 2) {
                System.out.println("Estudiantes aprobados:");
                for (Estudiante estudiante : listaEstudiantes) {
                    if (estudiante.getNotaFinal() >= 6.0) {
                        estudiante.mostrarInformacion();
                        System.out.println("-----------------------");
                    }
                }
            } else if (opcion == 3) {
                System.out.println("Saliendo del sistema. ¡Hasta luego!");
                break;
            } else {
                System.out.println("Opción no válida. Por favor, intente de nuevo.");
            }
        }


        sc.close();
    }
}
